c:\tc\tcc -mh -N -oc:\leaf\out\pcspeak.obj -c src\pcspeak.c
c:\tc\tcc -mh -N -oc:\leaf\out\video.obj -c src\video.c
c:\tc\tcc -mh -N -oc:\leaf\out\bmp.obj -c src\bmp.c
c:\tc\tcc -mh -N -oc:\leaf\out\mouse.obj -c src\mouse.c
c:\tc\tcc -mh -N -oc:\leaf\out\pcx.obj -c src\pcx.c
c:\tc\tcc -mh -N -oc:\leaf\out\tiff.obj -c src\tiff.c
c:\tc\tcc -mh -N -oc:\leaf\out\lengine.obj -c src\lengine.c
c:\tc\tlink c:\leaf\out\pcspeak.obj c:\leaf\out\video.obj c:\leaf\out\bmp.obj c:\leaf\out\mouse.obj c:\leaf\out\pcx.obj c:\leaf\out\tiff.obj c:\leaf\out\lengine.obj
echo Finished
